# Generated by Django 4.0.4 on 2023-01-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_minutes_recipe_sodium_recipe_sugar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(null=True, through='recipes.RecipeIngredient', to='recipes.ingredient'),
        ),
    ]
