# Generated by Django 4.0.4 on 2023-01-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_description_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='measurement',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
